### ISSUE TITLE
Can't make library through admin

### ISSUE THREAD

**Issue by lloydpick** [Floppy/van_dam#571]
Just went into the admin panel to make a new library, couldn't do it, this was the stacktrace...

```
I, [2022-06-28T22:47:29.495045 #23]  INFO -- : [18742918-2f11-4eee-925c-19c344655ca2] method=GET path=/admin/libraries/new format=html controller=Admin::LibrariesController action=new status=200 duration=23.87 view=18.35 db=1.70
I, [2022-06-28T22:47:41.653389 #23]  INFO -- : [cfb98afb-5b17-4483-93cc-351bd0f01fe9] method=POST path=/admin/libraries format=html controller=Admin::LibrariesController action=create status=500 duration=6.21 view=0.00 db=1.62
F, [2022-06-28T22:47:41.654472 #23] FATAL -- : [cfb98afb-5b17-4483-93cc-351bd0f01fe9]   
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
[cfb98afb-5b17-4483-93cc-351bd0f01fe9]   
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activemodel (7.0.3) lib/active_model/forbidden_attributes_protection.rb:23:in `sanitize_for_mass_assignment'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activemodel (7.0.3) lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activeadmin (2.13.1) lib/active_admin/resource_controller/data_access.rb:301:in `assign_attributes'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activeadmin (2.13.1) lib/active_admin/resource_controller/data_access.rb:119:in `build_resource'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] inherited_resources (1.13.1) lib/inherited_resources/actions.rb:31:in `create'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/abstract_controller/base.rb:215:in `process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actiontext (7.0.3) lib/action_text/rendering.rb:20:in `with_renderer'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actiontext (7.0.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `instance_exec'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/notifications.rb:206:in `block in instrument'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/notifications.rb:206:in `instrument'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activerecord (7.0.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/abstract_controller/base.rb:151:in `process'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionview (7.0.3) lib/action_view/rendering.rb:39:in `process'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal.rb:188:in `dispatch'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_controller/metal.rb:251:in `dispatch'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rails-settings-cached (2.8.2) lib/rails-settings/middleware.rb:9:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/tempfile_reaper.rb:15:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/conditional_get.rb:40:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/head.rb:12:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/session/abstract/id.rb:266:in `context'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/session/abstract/id.rb:260:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/cookies.rb:697:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] lograge (0.12.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] railties (7.0.3) lib/rails/rack/logger.rb:25:in `block in call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `block in tagged'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/tagged_logging.rb:38:in `tagged'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `tagged'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] railties (7.0.3) lib/rails/rack/logger.rb:25:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/method_override.rb:24:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/runtime.rb:22:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/static.rb:23:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] actionpack (7.0.3) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] railties (7.0.3) lib/rails/engine.rb:530:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] puma (5.6.4) lib/puma/configuration.rb:252:in `call'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] puma (5.6.4) lib/puma/server.rb:441:in `process_client'
[cfb98afb-5b17-4483-93cc-351bd0f01fe9] puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

On version v0.20.0 (bd347754)

**Comment by Floppy** [comment]
Good point, I should turn that off. The admin interface shouldn't be used for making new things, this is just the default behaviour for activeadmin.
